server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: test1234
    url: jdbc:mariadb://localhost:3306/testdb?serverTimezone=Asia/Seoul
    
  jpa:
    open-in-view: true #true - LAZY로딩 ok/ false - LAZY로딩 no
    hibernate:     
      ddl-auto: none  # create, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true        
  mail: # gmail smtp 설정    host: smtp.gmail.com
    port: 587
    username: 자신의이메일주소
    password: 비밀번호    properties:      mail:
        smtp:
          auth: true
          starttls: 
            enable: true      